
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.10.91:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.30.113
    port: 6379
server:
  servlet:
    context-path: /sell
  port: 8080
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  mpAppId: wx2cdc9155eaaa22e7
  mpAppSecret: b3ad29d0bd6d30f7cb40a52cfd0203d6
  openAppId: wx6ad144e54af67d87
  openAppSecret: b3ad29d0bd6d30f7cb40a52cfd0203d6
  mchId:  gh_81ec7e6f9d0e
#  mchKey: 06C56A89949D617xxxxxxxxxxx
#  keyPath: /var/weixin_cert/h5.p12
#  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
#  templateId:
#    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
#
url-config:
  wechatMpAuthorize: http://5tvyjr.natappfree.cc
  wechatOpenAuthorize: http://5tvyjr.natappfree.cc
  sell: http://5tvyjr.natappfree.cc
